"""
report.py — Phase 6: Human-readable report renderer.

Takes output from predict.py and formats it as a clean markdown report.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def render_report(result: dict) -> str:
    """
    Format a prediction result dict into a readable markdown report.

    Parameters
    ----------
    result : dict
        Output of predict_player().

    Returns
    -------
    str: formatted report string
    """
    player = result.get("player", "Unknown")
    source = result.get("source_league", "?")
    target = result.get("target_league", "?")
    src_lsc = result.get("source_lsc", "?")
    tgt_lsc = result.get("target_lsc", "?")

    g90  = result.get("projected_goals_p90")
    a90  = result.get("projected_assists_p90")
    xg90 = result.get("projected_xg_p90")
    xag90= result.get("projected_xag_p90")
    ci_lo= result.get("ci_low_goals")
    ci_hi= result.get("ci_high_goals")
    mins = result.get("minutes_expectation")
    adapt= result.get("adaptation_score_pct")
    risk = result.get("risk_score_pct")
    factors = result.get("top_5_factors", [])

    def fmt(v):
        if v is None:
            return "N/A"
        return f"{v:.3f}"

    def pct(v):
        if v is None:
            return "N/A"
        return f"{v:.1f}%"

    tgt_team = result.get("target_team")
    tgt_team_str = result.get("target_team_strength_ratio")

    report_lines = [
        "=" * 60,
        f"  CLPTM — Transfer Performance Projection",
        "=" * 60,
        f"",
        f"  Player        : {player}",
        f"  Transfer      : {source}  →  {target}" + (f" ({tgt_team})" if tgt_team else ""),
        f"  League Diff   : LSC {src_lsc:.2f} → {tgt_lsc:.2f}",
    ]
    if tgt_team:
        report_lines.append(f"  Target Team   : {tgt_team} (Relative Strength: {tgt_team_str:.2f}x)" if tgt_team_str else f"  Target Team   : {tgt_team}")

    report_lines.extend([
        f"",
        "─" * 60,
        "  📊 PROJECTED STATISTICS",
        "─" * 60,
        f"  Goals per 90    : {fmt(g90)}  (95% CI: {fmt(ci_lo)} – {fmt(ci_hi)})",
        f"  Assists per 90  : {fmt(a90)}",
        f"  xG per 90       : {fmt(xg90)}",
        f"  xAG per 90      : {fmt(xag90)}",
        f"  Minutes expect. : {int(mins) if mins else 'N/A'} min",
        f"",
        "─" * 60,
        "  🎯 ADAPTATION & RISK",
        "─" * 60,
        f"  Adaptation Score : {pct(adapt)}",
        f"  Risk Score       : {pct(risk)}",
        f"",
        "─" * 60,
        "  🔍 TOP 5 DRIVING FACTORS",
        "─" * 60,
    ])

    if factors:
        for i, factor in enumerate(factors, 1):
            direction = "▲" if factor.get("direction") == "positive" else "▼"
            label = factor.get("label", factor.get("feature", "?"))
            shap_val = factor.get("shap_value", 0)
            report_lines.append(f"  {i}. {direction} {label}  (SHAP: {shap_val:+.4f})")
    else:
        report_lines.append("  No SHAP factors available (models may need training).")

    report_lines += [
        f"",
        "=" * 60,
        "  Generated by CLPTM v1.0 — Cross-League Performance Translation Model",
        "=" * 60,
    ]

    return "\n".join(report_lines)


if __name__ == "__main__":
    # Demo with dummy data
    demo = {
        "player": "Florian Wirtz",
        "source_league": "Bundesliga",
        "target_league": "Premier League",
        "source_lsc": 0.92,
        "target_lsc": 1.00,
        "projected_goals_p90": 0.38,
        "projected_assists_p90": 0.29,
        "projected_xg_p90": 0.35,
        "projected_xag_p90": 0.22,
        "ci_low_goals": 0.21,
        "ci_high_goals": 0.55,
        "minutes_expectation": 2200,
        "adaptation_score_pct": 72.5,
        "risk_score_pct": 18.3,
        "top_5_factors": [
            {"label": "xG per 90 (league-adjusted)", "direction": "positive", "shap_value": 0.082},
            {"label": "Age curve score (peak = 24–28)", "direction": "positive", "shap_value": 0.071},
            {"label": "Team strength (relative to league avg)", "direction": "negative", "shap_value": -0.044},
            {"label": "Progressive passes per 90", "direction": "positive", "shap_value": 0.038},
            {"label": "Source league strength coefficient", "direction": "negative", "shap_value": -0.029},
        ],
    }
    print(render_report(demo))
